Lesson 1
Entrerry/TestGuru pull request #1
Opened 2022-08-30 18:32 UTC by Entrerry

Add locales, add version, add about page, add about/author page, edit readme.

2022-08-30 20:10 UTC, BubuntuClu requested changes

2022-08-30 20:10 UTC, BubuntuClu commented on app/controllers/static_pages_controller.rb
> +class StaticPagesController < ApplicationController
для статичных страниц контроллер/роут/вьюха не нужны. нужна только статичная страница в папке `public`

2022-08-30 20:10 UTC, BubuntuClu commented on app/views/static_pages/about.author.html.erb
> +<p><a href="https://github.com/Entrerry/TestGuru">GitHub</a></p>
ссылки на сторонние ресурсы открываем в новой ссылке

2022-08-30 20:10 UTC, BubuntuClu commented on app/views/static_pages/about.html.erb
> +<p><a href="https://thinknetica.com">Visit School</a></p>
ссылки на сторонние ресурсы открываем в новой ссылке

2022-08-30 20:10 UTC, BubuntuClu commented on config/initializers/version.rb
> +  VERSION = '0.0.1'
версия приложения начинается с другой версии

2022-08-30 20:10 UTC, BubuntuClu commented on config/routes.rb
> +  get 'static_pages/about'
это лишнее, в статичных страницах роутинг не участвует.

2022-08-31 04:54 UTC, closed without merging

2022-08-31 04:54 UTC, Entrerry commented
closed